name: eosc-556-project
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - jupyter
  - numpy
  - scipy
  - simpeg
  - matplotlib
  - python=3.11
  - pytest
  - pandas
  # solver
# uncomment the next line if you are on an intel platform
  # - pydiso # if on intel pc
# uncomment this line if you want to install mumps solvers
  - python-mumps